services:
  flutter-dev:
    build: .
    volumes:
      - ./:/app 
    ports:
      - "39421:39421"
    stdin_open: true
    tty: true
    command: flutter run -d web-server --web-port 39421 --web-hostname 0.0.0.0
