version: '3.8'

services:
  flutter-dev:
    build: .
    container_name: flutter-web-dev
    volumes:
      - ./:/app
    ports:
      - "39421:39421"
    stdin_open: true
    tty: true
    privileged: true
    working_dir: /app
    command: bash ##flutter run -d web-server --web-port 39421 --web-hostname 0.0.0.0 --verbose
