org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
# SOLUCIÓN TEMPORAL - Se eliminará automáticamente después de migrar el proyecto
# Ver SOLUCION_RUTA_DEFINITIVA.md para migración
android.overridePathCheck=true
